# Generated by Django 4.0.3 on 2022-05-12 13:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Nation',
            fields=[
                ('id', models.IntegerField()),
                ('name', models.CharField(max_length=160, primary_key=True, serialize=False)),
                ('description', models.TextField()),
                ('facebook_Link', models.CharField(blank=True, max_length=160, null=True)),
                ('site_Link', models.CharField(blank=True, max_length=160, null=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=5, max_digits=8, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=5, max_digits=8, null=True)),
                ('address', models.CharField(blank=True, max_length=160, null=True)),
                ('logo', models.CharField(blank=True, max_length=160, null=True)),
                ('marker', models.CharField(blank=True, max_length=160, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=160)),
                ('starttime', models.DateTimeField(blank=True, null=True)),
                ('endtime', models.DateTimeField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=280, null=True)),
                ('link', models.TextField()),
                ('description', models.TextField()),
                ('nation', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='NationsInnDb.nation')),
            ],
        ),
    ]
