# Generated by Django 4.0.3 on 2022-05-17 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NationsInnDb', '0002_alter_event_link_alter_event_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='logo',
            field=models.CharField(blank=True, max_length=160, null=True),
        ),
    ]
